package com.example.unidos;
//changeq
import androidx.appcompat.app.AppCompatActivity;
import androidx.databinding.DataBindingUtil;
import androidx.lifecycle.Observer;
import androidx.lifecycle.ViewModelProvider;
import android.app.DatePickerDialog;
import android.content.Context;
import android.os.Bundle;
import android.text.InputFilter;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.DatePicker;
import android.widget.ProgressBar;
import android.widget.Toast;

import java.util.Calendar;
import java.util.Date;

import com.example.unidos.databinding.ActivityNewAccountBinding;
import com.google.android.material.textfield.TextInputLayout;


public class NewAccount extends AppCompatActivity {
    String selectedDate, selectedSex;
    private Messages msg = new Messages();
    private  static final String[] options = new String[]{"Hombre", "Mujer"};
    AutoCompleteTextView sex;
    ProgressBar progressBar;
    TextInputLayout curp;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        /** The autogenerated class LoginBinding
         * is bound with the layout activity_new_account. **/
        final ActivityNewAccountBinding naBinding = DataBindingUtil.setContentView(this, R.layout.activity_new_account);
        /** An instance of the class LoginViewModel
         * which will be bound to the activity_new_account layout **/
        final NewAccountViewModel naViewModel = ViewModelProvider.AndroidViewModelFactory.getInstance(this.getApplication()).create(NewAccountViewModel.class);
        final PersistentData persistentData =  new PersistentData(this);

        persistentData.checkExistence();

        /** To indicate which is the ViewModel of the Binding class **/
        naBinding.setVmNewAc(naViewModel);
        /** This class will be owner of "binding". **/
        naBinding.setLifecycleOwner(this);
        /** set list values to true or false to keep the
         * button create account disabled on app start **/
        naViewModel.fill();
        /** Identify the AutoCompleteTextView. */
        sex = findViewById(R.id.outlined_exposed_dropdown);

        /** we'll be observing and waiting for the layout
         * component date changes. **/
        /** In this case the value will change when the
         * user presses the edit text. **/
        naViewModel.btDate.observe(this, new Observer<Boolean>() {
            @Override
            public void onChanged(Boolean s) {
                if(s){
                    System.out.println("DEBO MOSTRAR EL DATEPICKER");
                    /** To configure the calendar befor displaying it. **/
                    DatePickerDialog datePickerDialog = setCalendar(NewAccount.this, naViewModel);
                    /** show the calendar */
                    datePickerDialog.show();
                }
            }
        });

        /** we'll be observing and waiting for the layout
         * component "sex" changes.
        *   In this case the value will change when the
         *   user presses the edit text. */
        naViewModel.btSex.observe(this, new Observer<Boolean>() {
            @Override
            public void onChanged(Boolean s) {
                if(s){
                    /** configure the dropDown */
                    setDropDownMenu(naViewModel);
                    sex.showDropDown();
                }
            }
        });

        /** we'll be observing and waiting for the
         * layout component "date" changes. */
        naViewModel.date.observe(this, new Observer<String>() {
            @Override
            public void onChanged(String s) {
                Log.d("--->", s);
                /** chackDate is in charge of the
                 * validation of the typed date. **/
                naViewModel.checkDate();
            }
        });

        /** we'll be observing and waiting for the
         * layout component "sex" changes. */
        naViewModel.sex.observe(this, new Observer<String>() {
            @Override
            public void onChanged(String s) {
                Log.d("--->", s);
                /** chackSex is in charge of the validation
                 * of the typed date. **/
                naViewModel.checkSex();
            }
        });

        /** we'll be observing and waiting for the
         * layout component "curp" changes. **/
        naViewModel.curp.observe(this, new Observer<String>() {
            @Override
            public void onChanged(String s) {
                curp.getEditText().setFilters(new InputFilter[]{new InputFilter.AllCaps()});
                Log.i("--->", s);
                /** checkField is in charge of the validation of the typed date.
                 * send a 0, the method wants to know which validation apply. **/
                naViewModel.checkField(0);
            }
        });

        /** The following observers will perform
         * the same actions from the method above **/
        naViewModel.name.observe(this, new Observer<String>() {
            @Override
            public void onChanged(String s) {
                Log.i("@@@@", s);
                naViewModel.checkField(1);
            }
        });

        naViewModel.secondName.observe(this, new Observer<String>() {
            @Override
            public void onChanged(String s) {
                Log.d("--->", s);
                naViewModel.checkField(2);
            }
        });

        naViewModel.surname.observe(this, new Observer<String>() {
            @Override
            public void onChanged(String s) {
                Log.d("--->", s);
                naViewModel.checkField(3);
            }
        });

        naViewModel.secondSurname.observe(this, new Observer<String>() {
            @Override
            public void onChanged(String s) {
                Log.d("--->", s);
                naViewModel.checkField(4);
            }
        });

        naViewModel.phone.observe(this, new Observer<String>() {
            @Override
            public void onChanged(String s) {
                Log.d("--->", s);
                naViewModel.checkField(7);
            }
        });
        /** end of the same behavior. **/

        /** we'll be observing and waiting for
         * the variable "dateError" changes. */
        naViewModel.dateError.observe(this, new Observer<Boolean>() {
            /** Every time the variable changes its state will do this */
            @Override
            public void onChanged(Boolean b) {
                /** Identify the editText */
                TextInputLayout date = findViewById(R.id.TilDate);
                date.setErrorEnabled(true);
                /** show an error message */
                if (b)
                    date.setError(msg.findMessage("empty"));
                else
                    date.setError(null);
            }
        });

        /** we'll be observing and waiting for
         * the variable "sexError" changes. **/
        naViewModel.sexError.observe(this, new Observer<Boolean>() {
            /** Every time the variable changes its state will do this **/
            @Override
            public void onChanged(Boolean b) {
                /** Identify the editText **/
                TextInputLayout sex = findViewById(R.id.TilGender);
                sex.setErrorEnabled(true);
                /** show an error message */
                if (b)
                    sex.setError(msg.findMessage("empty"));
                else
                    sex.setError(null);
            }
        });

        /** we'll be observing and waiting for
         * the variable "error" changes. **/
        naViewModel.errors.observe(this, new Observer<String>() {
            @Override
            /** get the updated value **/
            public void onChanged(String s) {
                /** Identify the fields in the layout **/
                curp = findViewById(R.id.TilCurp);
                curp.setErrorEnabled(true);
                TextInputLayout name = findViewById(R.id.TilName);
                name.setErrorEnabled(true);
                TextInputLayout secondName = findViewById(R.id.TilName2);
                secondName.setErrorEnabled(true);
                TextInputLayout surname = findViewById(R.id.TilLastName1);
                surname.setErrorEnabled(true);
                TextInputLayout secondSurname = findViewById(R.id.TilLastName2);
                secondSurname.setErrorEnabled(true);
                TextInputLayout phone = findViewById(R.id.TilPhone);
                phone.setErrorEnabled(true);
                /** Lets check the action to execute. **/
                switch (s){
                    /** The field "CURP" is empty **/
                    case "emptyCurp":
                        /** Show message error. **/
                        curp.setError(msg.findMessage("empty"));
                        break;
                        /** The value "CURP" is correct **/
                    case "fillCurp":
                        /** disappear the error **/
                        curp.setErrorEnabled(false);
                        break;
                        /** the CURP value doesn´t match
                         * with the regular expression. **/
                    case "wrongSyntaxCurp":
                        System.out.println("holaa");
                        /** enable the error section and
                         * show error message under the field. **/
                        curp.setErrorEnabled(true);
                        curp.setError(msg.findMessage("noCURPmatch"));
                        break;
                        /** The name field is empty**/
                    case "emptyName":
                        /** show error message under the field**/
                        name.setError(msg.findMessage("empty"));
                        break;
                        /** the value of the name
                         * matches the regular expression */
                    case "fillName":
                        /** Disappear error message. **/
                        name.setErrorEnabled(false);
                        break;
                    /** the value of the name doesn´t match
                     * the regular expression **/
                    case "wrongSyntaxName":
                        name.setError(msg.findMessage("noNameMatch"));
                        break;
                    /** the value of the secondName doesn´t
                     * match the regular expression **/
                    case "wrongSyntaxName2":
                        secondName.setError(msg.findMessage("noNameMatch"));
                        break;
                    /** the value of the name2 matches
                     * the regular expression **/
                    case "fillName2":
                        secondName.setErrorEnabled(false);
                        break;
                        /** the surname field is empty **/
                    case "emptySurname":
                        surname.setError(msg.findMessage("empty"));
                        break;
                    /** the surname value matches
                     * the regular expression **/
                    case "fillSurname":
                        surname.setErrorEnabled(false);
                        break;
                    /** the surname value doesn't match
                     *  the regular expression **/
                    case "wrongSyntaxSurname":
                        surname.setError(msg.findMessage("noNameMatch"));
                        break;
                    /** the secondSurname value doesn't match
                     * the regular expression **/
                    case "wrongSyntaxSurname2":
                        secondSurname.setError(msg.findMessage("noNameMatch"));
                        break;
                    /** the secondSurname value matches
                     *  the regular expression **/
                    case "fillSurname2":
                        secondSurname.setErrorEnabled(false);
                        break;
                        /** the phone field is empty **/
                    case "emptyPhone":
                        phone.setError(msg.findMessage("empty"));
                        break;
                    /** the phone value matches the regular expression **/
                    case "fillPhone":
                        phone.setErrorEnabled(false);
                        break;
                    /** the phone value doesn't match
                     * the regular expression **/
                    case "wrongSyntaxPhone":
                        phone.setError(msg.findMessage("noPhoneMatch"));
                        break;
                }
            }
        });

        /** we'll be observing and waiting
         * for the variable "actionBtNewAcc" changes. **/
        naViewModel.actionBtNewAcc.observe(this, new Observer<String>() {
            @Override
            public void onChanged(String s) {
                progressBar = findViewById(R.id.progress_circular);
                Log.i("---> pb", s);
                switch (s){
                    /** Just show the progress bar **/
                    case "showProgressBar":
                        progressBar.setVisibility(View.VISIBLE);
                        naViewModel.setContext(NewAccount.this);
                        break;
                        /** Phone verification fail **/
                    case "hideProgressBar:fail":
                        /** Show error message **/
                        newAccountDoSomething(msg.findMessage("phoneVerifFail"));
                        break;
                        /** The CURP is already registered. **/
                    case "hideProgressBar:existingCURP":
                        /** Show error message **/
                        newAccountDoSomething(msg.findMessage("usrFound"));
                        break;
                        /** Something wrong happend on a firebase operation. **/
                    case "hideProgresBar:operationFail":
                        newAccountDoSomething(msg.findMessage("fail"));
                        break;
                        /** Succesful insertion **/
                    case "hideProgressBar:successInserting":
                        /** show message **/
                        newAccountDoSomething(msg.findMessage("opSuccess"));
                        /** call method to store the CURP and keep log */
                        persistentData.setValues(naViewModel.getCURP());
                        break;
                        /** The phone is already registered **/
                    case "hideProgressBar:existingPhone":
                        newAccountDoSomething(msg.findMessage("phoneFound"));
                        break;
                        /** The Internet connection is not stable **/
                    case "hideProgressBar:hasntInternet":
                        newAccountDoSomething(msg.findMessage("badConn"));
                        break;
                        /** The phone is not connected to Internet. **/
                    case "hideProgressBar:noConnected":
                        newAccountDoSomething(msg.findMessage("noConn"));
                        break;
                }
            }
        });
    }

    /** Show informative toast messages. **/
    public void newAccountDoSomething(String message){
        progressBar.setVisibility(View.GONE);
        Toast.makeText(getApplicationContext(), message, Toast.LENGTH_LONG).show();
    }

    public DatePickerDialog setCalendar(Context context, final NewAccountViewModel newAccountViewModel){
        final Calendar c = Calendar.getInstance();
        /** get the day, month and year **/
        final int mYear = c.get(Calendar.YEAR), mMonth = c.get(Calendar.MONTH), mDay = c.get(Calendar.DAY_OF_MONTH);
        /** The listener indicate the user has finished selecting a date. **/
        DatePickerDialog datePickerDialog=new DatePickerDialog(
                this, new DatePickerDialog.OnDateSetListener() {
            @Override
            public void onDateSet(DatePicker view, int year, int month, int dayOfMonth) {
                /** set a date right format to a variable. **/
                if(dayOfMonth<10 && month<10) {
                    selectedDate = "0"+dayOfMonth + "/0" + (month+1) + "/" + year;
                }else if(dayOfMonth<10)
                    selectedDate = "0"+dayOfMonth + "/" + (month+1) + "/" + year;
                else if(month<10)
                    selectedDate = dayOfMonth + "/0" + (month+1) + "/" + year;
                else
                    selectedDate = ""+dayOfMonth + "/" + (month+1) + "/" + year;
                /** call to the method in order to pass the date selected on every click **/
                newAccountViewModel.setDate(selectedDate);
            }
        }, mYear, mMonth, mDay);

        /** Configure the date to display, the system wont allow register minors **/
        Date today= new Date();
        c.setTime(today);
        c.add(Calendar.YEAR, -18);
        long maxDate = c.getTime().getTime();
        datePickerDialog.getDatePicker().setMaxDate(maxDate);
        c.setTime(today);
        c.add(Calendar.YEAR, -100);
        long minDate= c.getTime().getTime();
        datePickerDialog.getDatePicker().setMinDate(minDate);
        return datePickerDialog;
    }


    /** to configure the dropdown menu */
    public void setDropDownMenu(final NewAccountViewModel navm){
        System.out.println("DEBO MOSTRAR EL MENÚ");
        ArrayAdapter<String> adapter = new ArrayAdapter<>(NewAccount.this, R.layout.dropdown_menu_popup_item, options);
        sex.setAdapter(adapter);
        sex.setOnItemClickListener(new AdapterView.OnItemClickListener(){
            /** To know which option was selected. **/
            public void onItemClick(AdapterView<?> arg0, View arg1, int arg2, long arg3){
                selectedSex = (String) arg0.getItemAtPosition(arg2);
                Log.i("SELECTED TEXT WAS---->", selectedSex);
                /** To send the value to NewAccountViewModel **/
                navm.sex.setValue(selectedSex);
            }
        });
    }

}
